version: '3.8'
services:
  db:
    image: mongo:8.0.3-noble
    restart: always
    volumes:
      - db_data:/data/db # Mount a volume for data persistence
    ports:
      - 27017:27017
  api:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/todos
      - PORT=3000 # Port for the Node.js application
    volumes:
      - ./logs:/app/logs
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.3
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/usr/src/app/logs
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  db_data:
